[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "photoshop-helper-2026"
version = "0.1.0"
description = "A Python-based utility for automating repetitive tasks in Adobe Photoshop. It allows users to batch process images and apply consistent filters. The tool includes a feature for automated layer organiz"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "roman-liu-io1902m2" }]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
photoshop_helper_2026 = "photoshop_helper_2026.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
